# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Send Email message

on:
  push:
    tags:
      - 'v*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
        # mail server settings
             server_address: smtp.gmail.com
             server_port: 465
            # user credentials
             username: ${{ secrets.EMAIL_USERNAME }}
             password: ${{ secrets.EMAIL_PASSWORD }}
            # email subject
             subject: Sprint of ${{ github.repository }} has completed
            # email body as text
             body: Sprint of ${{ github.repository }} has completed and release.
            # comma-separated string, send email to
             to: ict.eti.consultants@gmail.com
            # from email name
             from: ETI Team 4 
